### ISSUE TITLE
Please make this example working with @nestjs apollo federation 10.x

### ISSUE THREAD

**Issue by tkssharma** [mrsauravsahu/blog-graphql-nestjs-fileupload#2]
After i update this example with these dependencies it breaks 

```
    "@apollo/federation": "^0.36.1",
    "@nestjs/apollo": "^10.0.11",
    "apollo-server-core": "^3.7.0",
    "@nestjs/graphql": "^10.0.11",
```

I am doing upload using gateway and gateway is using this upload APIs, I am always getting 
`TypeError: createReadStream is not a function
I did enough research on this and want this working 

 we can't remove `apollo-server-core` which depends on @nestjs/apollo
 so I am stuck here on how to get this upload working,
 
 with above same example things won't work with latest nestjs apollo migration to support federation

**Comment by mrsauravsahu** [comment]
Can you create a simple repo which shows the error?

**Comment by tkssharma** [comment]
Here we have 
[Github Repo](https://github.com/tkssharma/graphql-upload-with-apollo-federation
)
any help on this much appreciated, now with this, I am getting a file with size 0
it's on top of your commits

**Comment by mrsauravsahu** [comment]
Looks like the structure of the `file` Type has changed. I'm yet to fix the types but changing the `const { createReadStream } = (file as any).file as any;` did the trick. 

I can see the uploaded file.


Does that solve the issue you were facing?

**Comment by mrsauravsahu** [comment]
I will create a full Apollo Federation example soon, but here's the fix - https://github.com/mrsauravsahu/blog-graphql-nestjs-fileupload-apollo-federation/settings

**Comment by tkssharma** [comment]
> I will create a full Apollo Federation example soon, but here's the fix - https://github.com/mrsauravsahu/blog-graphql-nestjs-fileupload-apollo-federation/settings

please make it public repo, i can't access

**Comment by mrsauravsahu** [comment]
I'd added the 'settings' in the link by accident, this should work https://github.com/mrsauravsahu/blog-graphql-nestjs-fileupload-apollo-federation
